### ISSUE TITLE
Setting "exclude" option in setup.cfg causes an error

### ISSUE THREAD

**Issue by lorin** [CraigJPerry/setuptools-pep8#3]
I'd like to have pep8 not check files in my `migrations` directory. I tried this in setup.cfg:

```
[pep8]
exclude=migrations
```

If I invoke this directly with pep8, it works fine:

```
$ pep8 --config=setup.cfg
```

On the other hand, if I invoke it with setuptools-pep8, I get an error:

```
$ python setup.py pep8
running pep8
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    test_suite='tests.main',
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/lorin/.virtualenvs/nimbis-shop/src/nimbis-core/setuptools_pep8-0.1.3-py2.7.egg/setuptools_pep8/setuptools_command.py", line 49, in run
    pep8style = StyleGuide(parse_argv=False, config_file=False, **config_opts)
  File "/Users/lorin/.virtualenvs/nimbis-shop/src/nimbis-core/pep8-1.4.6-py2.7.egg/pep8.py", line 1591, in __init__
    options.exclude[index] = value.rstrip('/')
TypeError: 'str' object does not support item assignment
```

**Comment by CraigJPerry** [comment]
Thanks for reporting, I can replicate the failure. I've added a [test for this](https://github.com/CraigJPerry/setuptools-pep8/commit/c385308b29538cb0db22856317aa1a58e8cf4f79).

I don't know off the top of my head what interaction between pep8, setuptools & my setuptools Command would cause the failure but i'll take a dig through and see.

**Comment by CraigJPerry** [comment]
Resolved for next release.

**Comment by CraigJPerry** [comment]
@lorin v0.1.4 is now on PyPI

**Comment by lorin** [comment]
Wow, from bug report to updated PyPi package in only a few hours! Very impressive. I'll check it out today.
