### ISSUE TITLE
No such file or directory: .../NEWS.rst

### ISSUE THREAD

**Issue by lorin** [CraigJPerry/setuptools-pep8#4]
I got the following error trying to install 0.1.4 into a virtualenv wtih pip:

```
IOError: [Errno 2] No such file or directory: '/Users/lorin/.virtualenvs/myvenv/build/setuptools-pep8/NEWS.rst'
```

Looks like NEWS.rst isn't included in the egg.

Here's the complete output

```
$ pip install setuptools-pep8
Downloading/unpacking setuptools-pep8
  Downloading setuptools-pep8-0.1.4.tar.gz
  Storing download in cache at ./.cache/pip/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fs%2Fsetuptools-pep8%2Fsetuptools-pep8-0.1.4.tar.gz
  Running setup.py egg_info for package setuptools-pep8
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/Users/lorin/.virtualenvs/myvenv/build/setuptools-pep8/setup.py", line 15, in <module>
        NEWS = open(os.path.join(here, 'NEWS.rst')).read()
    IOError: [Errno 2] No such file or directory: '/Users/lorin/.virtualenvs/myvenv/build/setuptools-pep8/NEWS.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/lorin/.virtualenvs/myvenv/build/setuptools-pep8/setup.py", line 15, in <module>

    NEWS = open(os.path.join(here, 'NEWS.rst')).read()

IOError: [Errno 2] No such file or directory: '/Users/lorin/.virtualenvs/myvenv/build/setuptools-pep8/NEWS.rst'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/lorin/.virtualenvs/myvenv/build/setuptools-pep8
Storing complete log in /Users/lorin/.pip/pip.log
```

**Comment by CraigJPerry** [comment]
I've pushed up v0.1.5 to PyPI which (only) fixes the missing entry in manifest.in

Thanks again for reporting.

**Comment by lorin** [comment]
Works for me.
